version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  main:
    build: .
    env_file: .env
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - DATA_DIR=/data
      - PYTHONPATH=/app/src
    volumes:
      - ./src:/app/src
      - ./api/static:/app/api/static
      - ./data:/app/data
    ports:
      - "8001:8001"
    depends_on: [redis]
    command: python main.py

  api:
    build: .
    env_file: .env
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - DATA_DIR=/data
      - PYTHONPATH=/app/src
    volumes:
      - ./src:/app/src
      - ./api/static:/app/api/static
      - ./data:/app/data
    ports:
      - "8000:8000"
    depends_on: [redis]
    command: python api_main.py

  worker_transcribe:
    build: .
    env_file: .env
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - DATA_DIR=/data
      - WHISPER_MODEL=${WHISPER_MODEL:-medium}
      - WHISPER_DEVICE=${WHISPER_DEVICE:-cpu}
      - WHISPER_COMPUTE_TYPE=${WHISPER_COMPUTE_TYPE:-int8}
      - WHISPER_FAST_MODE=${WHISPER_FAST_MODE:-false}
      - TRANSCRIBE_SERVER_PORT=${TRANSCRIBE_SERVER_PORT:-8002}
      - PYTHONPATH=/app/src
    volumes:
      - ./src:/app/src
      - ./data:/data
    ports:
      - "8002:8002"
    depends_on: [redis]
    command: python transcribe_server.py

  worker_summarize:
    build: .
    env_file: .env
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - DATA_DIR=/data
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DEEPSEEK_MODEL=${DEEPSEEK_MODEL:-deepseek-chat}
      - PYTHONPATH=/app/src
    volumes:
      - ./src:/app/src
      - ./data:/data
    depends_on: [redis]
    command: sh -c "cd /app && PYTHONPATH=/app/src rq worker -u ${REDIS_URL:-redis://redis:6379} sum"
